name: 'ticketmaster'
version: '1.0.0'
config-version: 2

profile: 'ticketmaster'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ticketmaster:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
